### ISSUE TITLE
No recommendations on `onDidOpenTextDocument` event 

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-lsp-server#13]
It looks like `onDidOpenTextDocument` events are not handled properly. See https://github.com/redhat-developer/rh-che/issues/101#issuecomment-308419210 for more information. Originally reported as https://github.com/openshiftio/openshift.io/issues/210.

**Comment by invincibleJai** [comment]
tested onDidOpen events , it's not getting triggered for certain Pom based on content. Details can be seen here
https://github.com/eclipse/che/issues/5843
