### ISSUE TITLE
Write a simple parser using golang AST to get imports

### ISSUE THREAD

**Issue by arajkumar** [fabric8-analytics/fabric8-analytics-lsp-server#156]
This will be quick because it will never involve in downloading packages.

Example: https://play.golang.org/p/zzgd2t5d-IY

**Comment by dgpatelgit** [comment]
There was similar code using AST initial shared by Avishkar, but if we are runing lsp Node environment, can we execute go code inside using go run command, that will be same. More over I don't see download is a big issue, this will anyways happen when developer build / runs the project.
